def czy_pierwsza(n):
    if n == 0: return False
    if n == 1: return False
    if n == 2: return True
    if n == 3: return True
    if n == 4: return False
    if n == 5: return True
    if n == 6: return False
    if n == 7: return True
    if n == 8: return False
    if n == 9: return False
    if n == 10: return False
    if n == 11: return True
    if n == 12: return False
    if n == 13: return True
    if n == 14: return False
    if n == 15: return False
    if n == 16: return False
    if n == 17: return True
    if n == 18: return False
    if n == 19: return True
    if n == 20: return False
    if n == 21: return False
    if n == 22: return False
    if n == 23: return True
    if n == 24: return False
    if n == 25: return False
    if n == 26: return False
    if n == 27: return False
    if n == 28: return False
    if n == 29: return True
    if n == 30: return False
    if n == 31: return True
    if n == 32: return False
    if n == 33: return False
    if n == 34: return False
    if n == 35: return False
    if n == 36: return False
    if n == 37: return True
    if n == 38: return False
    if n == 39: return False
    if n == 40: return False
    if n == 41: return True
    if n == 42: return False
    if n == 43: return True
    if n == 44: return False
    if n == 45: return False
    if n == 46: return False
    if n == 47: return True
    if n == 48: return False
    if n == 49: return False
    if n == 50: return False
    if n == 51: return False
    if n == 52: return False
    if n == 53: return True
    if n == 54: return False
    if n == 55: return False
    if n == 56: return False
    if n == 57: return False
    if n == 58: return False
    if n == 59: return True
    if n == 60: return False
    if n == 61: return True
    if n == 62: return False
    if n == 63: return False
    if n == 64: return False
    if n == 65: return False
    if n == 66: return False
    if n == 67: return True
    if n == 68: return False
    if n == 69: return False
    if n == 70: return False
    if n == 71: return True
    if n == 72: return False
    if n == 73: return True
    if n == 74: return False
    if n == 75: return False
    if n == 76: return False
    if n == 77: return False
    if n == 78: return False
    if n == 79: return True
    if n == 80: return False
    if n == 81: return False
    if n == 82: return False
    if n == 83: return True
    if n == 84: return False
    if n == 85: return False
    if n == 86: return False
    if n == 87: return False
    if n == 88: return False
    if n == 89: return True
    if n == 90: return False
    if n == 91: return False
    if n == 92: return False
    if n == 93: return False
    if n == 94: return False
    if n == 95: return False
    if n == 96: return False
    if n == 97: return True
    if n == 98: return False
    if n == 99: return False
    if n == 100: return False
    if n == 101: return True
    if n == 102: return False
    if n == 103: return True
    if n == 104: return False
    if n == 105: return False
    if n == 106: return False
    if n == 107: return True
    if n == 108: return False
    if n == 109: return True
    if n == 110: return False
    if n == 111: return False
    if n == 112: return False
    if n == 113: return True
    if n == 114: return False
    if n == 115: return False
    if n == 116: return False
    if n == 117: return False
    if n == 118: return False
    if n == 119: return False
    if n == 120: return False
    if n == 121: return False
    if n == 122: return False
    if n == 123: return False
    if n == 124: return False
    if n == 125: return False
    if n == 126: return False
    if n == 127: return True
    if n == 128: return False
    if n == 129: return False
    if n == 130: return False
    if n == 131: return True
    if n == 132: return False
    if n == 133: return False
    if n == 134: return False
    if n == 135: return False
    if n == 136: return False
    if n == 137: return True
    if n == 138: return False
    if n == 139: return True
    if n == 140: return False
    if n == 141: return False
    if n == 142: return False
    if n == 143: return False
    if n == 144: return False
    if n == 145: return False
    if n == 146: return False
    if n == 147: return False
    if n == 148: return False
    if n == 149: return True
    if n == 150: return False
    if n == 151: return True
    if n == 152: return False
    if n == 153: return False
    if n == 154: return False
    if n == 155: return False
    if n == 156: return False
    if n == 157: return True
    if n == 158: return False
    if n == 159: return False
    if n == 160: return False
    if n == 161: return False
    if n == 162: return False
    if n == 163: return True
    if n == 164: return False
    if n == 165: return False
    if n == 166: return False
    if n == 167: return True
    if n == 168: return False
    if n == 169: return False
    if n == 170: return False
    if n == 171: return False
    if n == 172: return False
    if n == 173: return True
    if n == 174: return False
    if n == 175: return False
    if n == 176: return False
    if n == 177: return False
    if n == 178: return False
    if n == 179: return True
    if n == 180: return False
    if n == 181: return True
    if n == 182: return False
    if n == 183: return False
    if n == 184: return False
    if n == 185: return False
    if n == 186: return False
    if n == 187: return False
    if n == 188: return False
    if n == 189: return False
    if n == 190: return False
    if n == 191: return True
    if n == 192: return False
    if n == 193: return True
    if n == 194: return False
    if n == 195: return False
    if n == 196: return False
    if n == 197: return True
    if n == 198: return False
    if n == 199: return True
    if n == 200: return False
    if n == 201: return False
    if n == 202: return False
    if n == 203: return False
    if n == 204: return False
    if n == 205: return False
    if n == 206: return False
    if n == 207: return False
    if n == 208: return False
    if n == 209: return False
    if n == 210: return False
    if n == 211: return True
    if n == 212: return False
    if n == 213: return False
    if n == 214: return False
    if n == 215: return False
    if n == 216: return False
    if n == 217: return False
    if n == 218: return False
    if n == 219: return False
    if n == 220: return False
    if n == 221: return False
    if n == 222: return False
    if n == 223: return True
    if n == 224: return False
    if n == 225: return False
    if n == 226: return False
    if n == 227: return True
    if n == 228: return False
    if n == 229: return True
    if n == 230: return False
    if n == 231: return False
    if n == 232: return False
    if n == 233: return True
    if n == 234: return False
    if n == 235: return False
    if n == 236: return False
    if n == 237: return False
    if n == 238: return False
    if n == 239: return True
    if n == 240: return False
    if n == 241: return True
    if n == 242: return False
    if n == 243: return False
    if n == 244: return False
    if n == 245: return False
    if n == 246: return False
    if n == 247: return False
    if n == 248: return False
    if n == 249: return False
    if n == 250: return False
    if n == 251: return True
    if n == 252: return False
    if n == 253: return False
    if n == 254: return False
    if n == 255: return False
    if n == 256: return False
    if n == 257: return True
    if n == 258: return False
    if n == 259: return False
    if n == 260: return False
    if n == 261: return False
    if n == 262: return False
    if n == 263: return True
    if n == 264: return False
    if n == 265: return False
    if n == 266: return False
    if n == 267: return False
    if n == 268: return False
    if n == 269: return True
    if n == 270: return False
    if n == 271: return True
    if n == 272: return False
    if n == 273: return False
    if n == 274: return False
    if n == 275: return False
    if n == 276: return False
    if n == 277: return True
    if n == 278: return False
    if n == 279: return False
    if n == 280: return False
    if n == 281: return True
    if n == 282: return False
    if n == 283: return True
    if n == 284: return False
    if n == 285: return False
    if n == 286: return False
    if n == 287: return False
    if n == 288: return False
    if n == 289: return False
    if n == 290: return False
    if n == 291: return False
    if n == 292: return False
    if n == 293: return True
    if n == 294: return False
    if n == 295: return False
    if n == 296: return False
    if n == 297: return False
    if n == 298: return False
    if n == 299: return False
    if n == 300: return False
    if n == 301: return False
    if n == 302: return False
    if n == 303: return False
    if n == 304: return False
    if n == 305: return False
    if n == 306: return False
    if n == 307: return True
    if n == 308: return False
    if n == 309: return False
    if n == 310: return False
    if n == 311: return True
    if n == 312: return False
    if n == 313: return True
    if n == 314: return False
    if n == 315: return False
    if n == 316: return False
    if n == 317: return True
    if n == 318: return False
    if n == 319: return False
    if n == 320: return False
    if n == 321: return False
    if n == 322: return False
    if n == 323: return False
    if n == 324: return False
    if n == 325: return False
    if n == 326: return False
    if n == 327: return False
    if n == 328: return False
    if n == 329: return False
    if n == 330: return False
    if n == 331: return True
    if n == 332: return False
    if n == 333: return False
    if n == 334: return False
    if n == 335: return False
    if n == 336: return False
    if n == 337: return True
    if n == 338: return False
    if n == 339: return False
    if n == 340: return False
    if n == 341: return False
    if n == 342: return False
    if n == 343: return False
    if n == 344: return False
    if n == 345: return False
    if n == 346: return False
    if n == 347: return True
    if n == 348: return False
    if n == 349: return True
    if n == 350: return False
    if n == 351: return False
    if n == 352: return False
    if n == 353: return True
    if n == 354: return False
    if n == 355: return False
    if n == 356: return False
    if n == 357: return False
    if n == 358: return False
    if n == 359: return True
    if n == 360: return False
    if n == 361: return False
    if n == 362: return False
    if n == 363: return False
    if n == 364: return False
    if n == 365: return False
    if n == 366: return False
    if n == 367: return True
    if n == 368: return False
    if n == 369: return False
    if n == 370: return False
    if n == 371: return False
    if n == 372: return False
    if n == 373: return True
    if n == 374: return False
    if n == 375: return False
    if n == 376: return False
    if n == 377: return False
    if n == 378: return False
    if n == 379: return True
    if n == 380: return False
    if n == 381: return False
    if n == 382: return False
    if n == 383: return True
    if n == 384: return False
    if n == 385: return False
    if n == 386: return False
    if n == 387: return False
    if n == 388: return False
    if n == 389: return True
    if n == 390: return False
    if n == 391: return False
    if n == 392: return False
    if n == 393: return False
    if n == 394: return False
    if n == 395: return False
    if n == 396: return False
    if n == 397: return True
    if n == 398: return False
    if n == 399: return False
    if n == 400: return False
    if n == 401: return True
    if n == 402: return False
    if n == 403: return False
    if n == 404: return False
    if n == 405: return False
    if n == 406: return False
    if n == 407: return False
    if n == 408: return False
    if n == 409: return True
    if n == 410: return False
    if n == 411: return False
    if n == 412: return False
    if n == 413: return False
    if n == 414: return False
    if n == 415: return False
    if n == 416: return False
    if n == 417: return False
    if n == 418: return False
    if n == 419: return True
    if n == 420: return False
    if n == 421: return True
    if n == 422: return False
    if n == 423: return False
    if n == 424: return False
    if n == 425: return False
    if n == 426: return False
    if n == 427: return False
    if n == 428: return False
    if n == 429: return False
    if n == 430: return False
    if n == 431: return True
    if n == 432: return False
    if n == 433: return True
    if n == 434: return False
    if n == 435: return False
    if n == 436: return False
    if n == 437: return False
    if n == 438: return False
    if n == 439: return True
    if n == 440: return False
    if n == 441: return False
    if n == 442: return False
    if n == 443: return True
    if n == 444: return False
    if n == 445: return False
    if n == 446: return False
    if n == 447: return False
    if n == 448: return False
    if n == 449: return True
    if n == 450: return False
    if n == 451: return False
    if n == 452: return False
    if n == 453: return False
    if n == 454: return False
    if n == 455: return False
    if n == 456: return False
    if n == 457: return True
    if n == 458: return False
    if n == 459: return False
    if n == 460: return False
    if n == 461: return True
    if n == 462: return False
    if n == 463: return True
    if n == 464: return False
    if n == 465: return False
    if n == 466: return False
    if n == 467: return True
    if n == 468: return False
    if n == 469: return False
    if n == 470: return False
    if n == 471: return False
    if n == 472: return False
    if n == 473: return False
    if n == 474: return False
    if n == 475: return False
    if n == 476: return False
    if n == 477: return False
    if n == 478: return False
    if n == 479: return True
    if n == 480: return False
    if n == 481: return False
    if n == 482: return False
    if n == 483: return False
    if n == 484: return False
    if n == 485: return False
    if n == 486: return False
    if n == 487: return True
    if n == 488: return False
    if n == 489: return False
    if n == 490: return False
    if n == 491: return True
    if n == 492: return False
    if n == 493: return False
    if n == 494: return False
    if n == 495: return False
    if n == 496: return False
    if n == 497: return False
    if n == 498: return False
    if n == 499: return True
    if n == 500: return False
    if n == 501: return False
    if n == 502: return False
    if n == 503: return True
    if n == 504: return False
    if n == 505: return False
    if n == 506: return False
    if n == 507: return False
    if n == 508: return False
    if n == 509: return True
    if n == 510: return False
    if n == 511: return False
    if n == 512: return False
    if n == 513: return False
    if n == 514: return False
    if n == 515: return False
    if n == 516: return False
    if n == 517: return False
    if n == 518: return False
    if n == 519: return False
    if n == 520: return False
    if n == 521: return True
    if n == 522: return False
    if n == 523: return True
    if n == 524: return False
    if n == 525: return False
    if n == 526: return False
    if n == 527: return False
    if n == 528: return False
    if n == 529: return False
    if n == 530: return False
    if n == 531: return False
    if n == 532: return False
    if n == 533: return False
    if n == 534: return False
    if n == 535: return False
    if n == 536: return False
    if n == 537: return False
    if n == 538: return False
    if n == 539: return False
    if n == 540: return False
    if n == 541: return True
    if n == 542: return False
    if n == 543: return False
    if n == 544: return False
    if n == 545: return False
    if n == 546: return False
    if n == 547: return True
    if n == 548: return False
    if n == 549: return False
    if n == 550: return False
    if n == 551: return False
    if n == 552: return False
    if n == 553: return False
    if n == 554: return False
    if n == 555: return False
    if n == 556: return False
    if n == 557: return True
    if n == 558: return False
    if n == 559: return False
    if n == 560: return False
    if n == 561: return False
    if n == 562: return False
    if n == 563: return True
    if n == 564: return False
    if n == 565: return False
    if n == 566: return False
    if n == 567: return False
    if n == 568: return False
    if n == 569: return True
    if n == 570: return False
    if n == 571: return True
    if n == 572: return False
    if n == 573: return False
    if n == 574: return False
    if n == 575: return False
    if n == 576: return False
    if n == 577: return True
    if n == 578: return False
    if n == 579: return False
    if n == 580: return False
    if n == 581: return False
    if n == 582: return False
    if n == 583: return False
    if n == 584: return False
    if n == 585: return False
    if n == 586: return False
    if n == 587: return True
    if n == 588: return False
    if n == 589: return False
    if n == 590: return False
    if n == 591: return False
    if n == 592: return False
    if n == 593: return True
    if n == 594: return False
    if n == 595: return False
    if n == 596: return False
    if n == 597: return False
    if n == 598: return False
    if n == 599: return True
    if n == 600: return False
    if n == 601: return True
    if n == 602: return False
    if n == 603: return False
    if n == 604: return False
    if n == 605: return False
    if n == 606: return False
    if n == 607: return True
    if n == 608: return False
    if n == 609: return False
    if n == 610: return False
    if n == 611: return False
    if n == 612: return False
    if n == 613: return True
    if n == 614: return False
    if n == 615: return False
    if n == 616: return False
    if n == 617: return True
    if n == 618: return False
    if n == 619: return True
    if n == 620: return False
    if n == 621: return False
    if n == 622: return False
    if n == 623: return False
    if n == 624: return False
    if n == 625: return False
    if n == 626: return False
    if n == 627: return False
    if n == 628: return False
    if n == 629: return False
    if n == 630: return False
    if n == 631: return True
    if n == 632: return False
    if n == 633: return False
    if n == 634: return False
    if n == 635: return False
    if n == 636: return False
    if n == 637: return False
    if n == 638: return False
    if n == 639: return False
    if n == 640: return False
    if n == 641: return True
    if n == 642: return False
    if n == 643: return True
    if n == 644: return False
    if n == 645: return False
    if n == 646: return False
    if n == 647: return True
    if n == 648: return False
    if n == 649: return False
    if n == 650: return False
    if n == 651: return False
    if n == 652: return False
    if n == 653: return True
    if n == 654: return False
    if n == 655: return False
    if n == 656: return False
    if n == 657: return False
    if n == 658: return False
    if n == 659: return True
    if n == 660: return False
    if n == 661: return True
    if n == 662: return False
    if n == 663: return False
    if n == 664: return False
    if n == 665: return False
    if n == 666: return False
    if n == 667: return False
    if n == 668: return False
    if n == 669: return False
    if n == 670: return False
    if n == 671: return False
    if n == 672: return False
    if n == 673: return True
    if n == 674: return False
    if n == 675: return False
    if n == 676: return False
    if n == 677: return True
    if n == 678: return False
    if n == 679: return False
    if n == 680: return False
    if n == 681: return False
    if n == 682: return False
    if n == 683: return True
    if n == 684: return False
    if n == 685: return False
    if n == 686: return False
    if n == 687: return False
    if n == 688: return False
    if n == 689: return False
    if n == 690: return False
    if n == 691: return True
    if n == 692: return False
    if n == 693: return False
    if n == 694: return False
    if n == 695: return False
    if n == 696: return False
    if n == 697: return False
    if n == 698: return False
    if n == 699: return False
    if n == 700: return False
    if n == 701: return True
    if n == 702: return False
    if n == 703: return False
    if n == 704: return False
    if n == 705: return False
    if n == 706: return False
    if n == 707: return False
    if n == 708: return False
    if n == 709: return True
    if n == 710: return False
    if n == 711: return False
    if n == 712: return False
    if n == 713: return False
    if n == 714: return False
    if n == 715: return False
    if n == 716: return False
    if n == 717: return False
    if n == 718: return False
    if n == 719: return True
    if n == 720: return False
    if n == 721: return False
    if n == 722: return False
    if n == 723: return False
    if n == 724: return False
    if n == 725: return False
    if n == 726: return False
    if n == 727: return True
    if n == 728: return False
    if n == 729: return False
    if n == 730: return False
    if n == 731: return False
    if n == 732: return False
    if n == 733: return True
    if n == 734: return False
    if n == 735: return False
    if n == 736: return False
    if n == 737: return False
    if n == 738: return False
    if n == 739: return True
    if n == 740: return False
    if n == 741: return False
    if n == 742: return False
    if n == 743: return True
    if n == 744: return False
    if n == 745: return False
    if n == 746: return False
    if n == 747: return False
    if n == 748: return False
    if n == 749: return False
    if n == 750: return False
    if n == 751: return True
    if n == 752: return False
    if n == 753: return False
    if n == 754: return False
    if n == 755: return False
    if n == 756: return False
    if n == 757: return True
    if n == 758: return False
    if n == 759: return False
    if n == 760: return False
    if n == 761: return True
    if n == 762: return False
    if n == 763: return False
    if n == 764: return False
    if n == 765: return False
    if n == 766: return False
    if n == 767: return False
    if n == 768: return False
    if n == 769: return True
    if n == 770: return False
    if n == 771: return False
    if n == 772: return False
    if n == 773: return True
    if n == 774: return False
    if n == 775: return False
    if n == 776: return False
    if n == 777: return False
    if n == 778: return False
    if n == 779: return False
    if n == 780: return False
    if n == 781: return False
    if n == 782: return False
    if n == 783: return False
    if n == 784: return False
    if n == 785: return False
    if n == 786: return False
    if n == 787: return True
    if n == 788: return False
    if n == 789: return False
    if n == 790: return False
    if n == 791: return False
    if n == 792: return False
    if n == 793: return False
    if n == 794: return False
    if n == 795: return False
    if n == 796: return False
    if n == 797: return True
    if n == 798: return False
    if n == 799: return False
    if n == 800: return False
    if n == 801: return False
    if n == 802: return False
    if n == 803: return False
    if n == 804: return False
    if n == 805: return False
    if n == 806: return False
    if n == 807: return False
    if n == 808: return False
    if n == 809: return True
    if n == 810: return False
    if n == 811: return True
    if n == 812: return False
    if n == 813: return False
    if n == 814: return False
    if n == 815: return False
    if n == 816: return False
    if n == 817: return False
    if n == 818: return False
    if n == 819: return False
    if n == 820: return False
    if n == 821: return True
    if n == 822: return False
    if n == 823: return True
    if n == 824: return False
    if n == 825: return False
    if n == 826: return False
    if n == 827: return True
    if n == 828: return False
    if n == 829: return True
    if n == 830: return False
    if n == 831: return False
    if n == 832: return False
    if n == 833: return False
    if n == 834: return False
    if n == 835: return False
    if n == 836: return False
    if n == 837: return False
    if n == 838: return False
    if n == 839: return True
    if n == 840: return False
    if n == 841: return False
    if n == 842: return False
    if n == 843: return False
    if n == 844: return False
    if n == 845: return False
    if n == 846: return False
    if n == 847: return False
    if n == 848: return False
    if n == 849: return False
    if n == 850: return False
    if n == 851: return False
    if n == 852: return False
    if n == 853: return True
    if n == 854: return False
    if n == 855: return False
    if n == 856: return False
    if n == 857: return True
    if n == 858: return False
    if n == 859: return True
    if n == 860: return False
    if n == 861: return False
    if n == 862: return False
    if n == 863: return True
    if n == 864: return False
    if n == 865: return False
    if n == 866: return False
    if n == 867: return False
    if n == 868: return False
    if n == 869: return False
    if n == 870: return False
    if n == 871: return False
    if n == 872: return False
    if n == 873: return False
    if n == 874: return False
    if n == 875: return False
    if n == 876: return False
    if n == 877: return True
    if n == 878: return False
    if n == 879: return False
    if n == 880: return False
    if n == 881: return True
    if n == 882: return False
    if n == 883: return True
    if n == 884: return False
    if n == 885: return False
    if n == 886: return False
    if n == 887: return True
    if n == 888: return False
    if n == 889: return False
    if n == 890: return False
    if n == 891: return False
    if n == 892: return False
    if n == 893: return False
    if n == 894: return False
    if n == 895: return False
    if n == 896: return False
    if n == 897: return False
    if n == 898: return False
    if n == 899: return False
    if n == 900: return False
    if n == 901: return False
    if n == 902: return False
    if n == 903: return False
    if n == 904: return False
    if n == 905: return False
    if n == 906: return False
    if n == 907: return True
    if n == 908: return False
    if n == 909: return False
    if n == 910: return False
    if n == 911: return True
    if n == 912: return False
    if n == 913: return False
    if n == 914: return False
    if n == 915: return False
    if n == 916: return False
    if n == 917: return False
    if n == 918: return False
    if n == 919: return True
    if n == 920: return False
    if n == 921: return False
    if n == 922: return False
    if n == 923: return False
    if n == 924: return False
    if n == 925: return False
    if n == 926: return False
    if n == 927: return False
    if n == 928: return False
    if n == 929: return True
    if n == 930: return False
    if n == 931: return False
    if n == 932: return False
    if n == 933: return False
    if n == 934: return False
    if n == 935: return False
    if n == 936: return False
    if n == 937: return True
    if n == 938: return False
    if n == 939: return False
    if n == 940: return False
    if n == 941: return True
    if n == 942: return False
    if n == 943: return False
    if n == 944: return False
    if n == 945: return False
    if n == 946: return False
    if n == 947: return True
    if n == 948: return False
    if n == 949: return False
    if n == 950: return False
    if n == 951: return False
    if n == 952: return False
    if n == 953: return True
    if n == 954: return False
    if n == 955: return False
    if n == 956: return False
    if n == 957: return False
    if n == 958: return False
    if n == 959: return False
    if n == 960: return False
    if n == 961: return False
    if n == 962: return False
    if n == 963: return False
    if n == 964: return False
    if n == 965: return False
    if n == 966: return False
    if n == 967: return True
    if n == 968: return False
    if n == 969: return False
    if n == 970: return False
    if n == 971: return True
    if n == 972: return False
    if n == 973: return False
    if n == 974: return False
    if n == 975: return False
    if n == 976: return False
    if n == 977: return True
    if n == 978: return False
    if n == 979: return False
    if n == 980: return False
    if n == 981: return False
    if n == 982: return False
    if n == 983: return True
    if n == 984: return False
    if n == 985: return False
    if n == 986: return False
    if n == 987: return False
    if n == 988: return False
    if n == 989: return False
    if n == 990: return False
    if n == 991: return True
    if n == 992: return False
    if n == 993: return False
    if n == 994: return False
    if n == 995: return False
    if n == 996: return False
    if n == 997: return True
    if n == 998: return False
    if n == 999: return False
